# Generated by Django 4.2.14 on 2024-08-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="publshed_date",
            new_name="published_date",
        ),
    ]
